### ISSUE TITLE
SwiftUI @Default(.key) not updating across multiple views.

### ISSUE THREAD

**Issue by RoyRao2333** [sindresorhus/Defaults#103] opened 2022-05-14 05:19 UTC
Here are the code snippets:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/31413093/168411832-dbca122f-9a25-4715-9b81-f5842109faea.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/31413093/168411642-9b793711-616d-4209-8fd7-26a7b84d7a39.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/31413093/168411644-860a7f4b-1b8f-4b5e-87dd-152654c2e65c.png">

As you can see, parent view and child view are both containing a private ```firstLaunch``` property. However, when child view changes the ```firstLaunch``` to ```false```, parent view is not updating. Although it do changed the value of this key in ```UserDefault``` since it shows ```HomeView``` on App's second launch...

I'm using the latest release of ```Defaults (6.2.1)```. Don't know if my usage is wrong? I do remember this can work in my previous projects.😂

**Comment by sindresorhus** [comment] 2022-05-14 06:16
Duplicate of #59

**Closed by sindresorhus** 2022-05-14 06:16 UTC
