### ISSUE TITLE
High CPU and Hign Memory increase

### ISSUE THREAD

**Issue by averyhome** [sindresorhus/Defaults#154] opened 2023-12-11 08:26 UTC
when i use like this

        .navigationDestination(isPresented: $isPushToHelp, destination: {
              SettingView()
        })

if  SettingView contains
     @Default(.hiddenAds) var hiddenAds
then the cup and memory will increase to the max

when i remove the  @Default(.hiddenAds) var hiddenAds 
it will be ok
please how can i resolve it

**Comment by sindresorhus** [comment] 2023-12-11 13:41
Duplicate of #146

**Closed by sindresorhus** 2023-12-11 13:41 UTC

**Comment by averyhome** [comment] 2023-12-11 13:54
> Duplicate of #146
oops， but i can not find any solution in #146 
or i need update the Defaults version?
