### ISSUE TITLE
Cannot conform to protocol on Xcode 13.3 beta - macOS 12.3

### ISSUE THREAD

**Issue by Wouter01** [sindresorhus/Defaults#93] opened 2022-01-28 19:14 UTC
Yesterday I updated Xcode to version 13.3, and now there are a number of errors about DefaultsSerializable.
When creating a new project and adding the example code from here, I get the same error.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/62355975/151607063-410afc4a-56bf-4537-908b-2a19b3a2b1df.png">

**Comment by sindresorhus** [comment] 2022-02-03 18:27
This looks like a Swift regression: https://bugs.swift.org/projects/SR/issues/SR-15807

**Comment by ibash** [comment] 2022-02-10 03:30
Workaround:

```
struct MyBridge<Value: Codable>: DefaultsCodableBridge {}

extension User: Defaults.Serializable {
  static let bridge = MyBridge<User>()
}
```

**Comment by quantamrhino** [comment] 2022-02-21 13:50
Any workaround for enums?

**Comment by sindresorhus** [comment] 2022-02-26 11:06
@hank121314 It doesn't look like Swift will fix this in time for Xcode 13.3 final. Any idea how we could work around this in Defaults for now?

**Comment by hank121314** [comment] 2022-02-27 05:46
This issue seems to occur when using the type which has multiple protocol conformance.
The temporary workaround might be declared the protocol conformance in the same module.
Here are my workaround steps:

1. Create `WorkAround.swift` in the module which is using `Defaults`.
2. Copy the codes below to `WorkAround.swift`
```swift
import Defaults
import Foundation

extension Defaults.Serializable where Self: Codable {
	public static var bridge: Defaults.TopLevelCodableBridge<Self> { Defaults.TopLevelCodableBridge() }
}

extension Defaults.Serializable where Self: Codable & NSSecureCoding {
	public static var bridge: Defaults.CodableNSSecureCodingBridge<Self> { Defaults.CodableNSSecureCodingBridge() }
}

extension Defaults.Serializable where Self: Codable & NSSecureCoding & Defaults.PreferNSSecureCoding {
	public static var bridge: Defaults.NSSecureCodingBridge<Self> { Defaults.NSSecureCodingBridge() }
}

extension Defaults.Serializable where Self: Codable & RawRepresentable {
	public static var bridge: Defaults.RawRepresentableCodableBridge<Self> { Defaults.RawRepresentableCodableBridge() }
}

extension Defaults.Serializable where Self: Codable & RawRepresentable & Defaults.PreferRawRepresentable {
	public static var bridge: Defaults.RawRepresentableBridge<Self> { Defaults.RawRepresentableBridge() }
}

extension Defaults.Serializable where Self: RawRepresentable {
	public static var bridge: Defaults.RawRepresentableBridge<Self> { Defaults.RawRepresentableBridge() }
}
extension Defaults.Serializable where Self: NSSecureCoding {
	public static var bridge: Defaults.NSSecureCodingBridge<Self> { Defaults.NSSecureCodingBridge() }
}

extension Defaults.CollectionSerializable where Element: Defaults.Serializable {
	public static var bridge: Defaults.CollectionBridge<Self> { Defaults.CollectionBridge() }
}

extension Defaults.SetAlgebraSerializable where Element: Defaults.Serializable & Hashable {
	public static var bridge: Defaults.SetAlgebraBridge<Self> { Defaults.SetAlgebraBridge() }
}
```

And to achieve this workaround we might also need to public some bridge initializers.
Not sure whether this is an acceptable solution.

**Comment by sindresorhus** [comment] 2022-02-28 14:26
Yeah, that's a good workaround.

**Comment by nab0y4enko** [comment] 2022-03-15 13:44
Have same issue on Release Xcode version 😢

**Comment by RoyRao2333** [comment] 2022-03-15 16:35
> Hi @nab0y4enko. I am working on this, sorry for the inconvenience 😞 .

It's always a mess after upgrading Xcode, especially with a newer Swift version... Thanks for the hard work anyway!

Hoping to see this issue to be fixed soon...

**Comment by sindresorhus** [comment] 2022-03-15 17:11
I recommend anyone looking here to also report this through Feedback Assistant. Just link to the Swift issue.

**Comment by owenzhao** [comment] 2022-03-16 03:14
Workaround + v6.2.1 worked.😄😄

**Comment by Maschina** [comment] 2022-03-16 10:23
To whom it may concern that have custom `Codable` struct/class and looking for workaround (using the example of `NSRect`):

```swift
extension NSRect: Defaults.Serializable {
	// TODO: A temporary workaround for Xcode 13.3 compiler issue. Should remove after https://bugs.swift.org/browse/SR-15807 is fixed.
	public static var bridge: Defaults.TopLevelCodableBridge<NSRect> { Defaults.TopLevelCodableBridge() }
}
```

**Comment by sindresorhus** [comment] 2022-05-06 09:20
@hank121314 Congrats on getting your pull request merged on the Swift repo: https://github.com/apple/swift/pull/42293 And thank you so much for fixing this issue in Swift 🎉

**Comment by sindresorhus** [comment] 2022-09-22 16:54
Closing as Xcode 14 is out now.

**Closed by sindresorhus** 2022-09-22 16:54 UTC
