### ISSUE TITLE
Color error: Type 'ColorStructTest' does not conform to protocol 'Decodable' or 'Encodable'

### ISSUE THREAD

**Issue by GanZhiXiong** [sindresorhus/Defaults#112] opened 2022-09-10 05:15 UTC
## My development environment
- Xcode 13.3
- macOS Monterey 12.3.1
- M1

## My code（macOS App）:
```swift
struct ColorStructTest: Identifiable, Defaults.Serializable, Codable {
  var id: String
  var name: String
  var color: Color
}
```

**Comment by sindresorhus** [comment] 2022-09-10 06:09
Duplicate of #111

**Comment by sindresorhus** [comment] 2022-09-10 06:10
In the future, please try to do some debugging yourself before opening an issue.

**Closed by sindresorhus** 2022-09-10 06:09 UTC

**Comment by GanZhiXiong** [comment] 2022-09-10 08:32
OK. Thank for you reply.
